export interface Listing {
  id: number;
  title: string;
  description?: string;
  description_en?: string;
  description_nl?: string;
  price?: number;
  bedrooms?: number;
  bathrooms?: number;
  area?: number;
  address?: string;
  city?: string;
  postal_code?: string;
  property_type?: string;
  status: string;
  listing_type?: 'sale' | 'rent';
  image_url?: string;
  images?: string[];
  featured: boolean;
  hidden?: boolean;
  created_at: string;
  // Luxury real estate fields
  year_built?: number;
  energy_label?: string;
  garden?: boolean;
  garden_area?: number;
  parking?: boolean;
  parking_spaces?: number;
  balcony?: boolean;
  terrace?: boolean;
  furnished?: boolean;
  basement?: boolean;
  elevator?: boolean;
  floors?: number;
  source_url?: string;
  renovation_year?: number;
  price_per_sqm?: number;
  asking_price?: string;
  availability_date?: string;
  hoa_fees?: number;
  property_tax?: number;
}

export const demoListings: Listing[] = [
  {
    id: 1,
    title: "Canal House on Prinsengracht",
    description: "An extraordinary 17th-century canal house on Prinsengracht, recently restored to its original grandeur. This 285m² residence features four bedrooms, three bathrooms, a private garden, and uninterrupted canal views. Original marble fireplaces, ornate ceiling roses, and hand-crafted oak floors have been meticulously preserved. The gourmet kitchen opens onto a south-facing terrace. A rare opportunity to own one of Amsterdam's most prestigious addresses.",
    price: 3250000,
    bedrooms: 4,
    bathrooms: 3,
    area: 285,
    address: "Prinsengracht 287",
    city: "Amsterdam",
    postal_code: "1016 HR",
    property_type: "house",
    status: "available",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1616137466211-f939a420be84?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    created_at: "2026-04-15T10:00:00Z",
    year_built: 1685,
    energy_label: "D",
    floors: 4,
    furnished: false,
    garden: true,
    garden_area: 45,
    balcony: false,
    terrace: true,
    parking: false,
    elevator: false,
    basement: true,
  },
  {
    id: 2,
    title: "Penthouse at Zuidas Towers",
    description: "A breathtaking 210m² penthouse in the heart of Amsterdam's financial district. Floor-to-ceiling windows frame panoramic city views, while the 80m² rooftop terrace with private jacuzzi offers an unparalleled entertaining space. Three ensuite bedrooms, a Bulthaup kitchen, and smart home automation throughout. Two private parking spaces included.",
    price: 2850000,
    bedrooms: 3,
    bathrooms: 3,
    area: 210,
    address: "Gustav Mahlerlaan 1020",
    city: "Amsterdam",
    postal_code: "1082 MA",
    property_type: "penthouse",
    status: "available",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    created_at: "2026-04-10T10:00:00Z",
    year_built: 2020,
    energy_label: "A+",
    floors: 1,
    furnished: false,
    garden: false,
    balcony: false,
    terrace: true,
    parking: true,
    parking_spaces: 2,
    elevator: true,
    basement: true,
  },
  {
    id: 3,
    title: "Jordaan Boutique Apartment",
    description: "A beautifully designed 125m² apartment in the historic Jordaan district. This two-bedroom residence blends modern Scandinavian design with original Amsterdam architectural details. Exposed brick walls, a mezzanine study, and a curated art collection make this a truly unique home. Steps from the Noordermarkt and the best cafés in the city.",
    price: 1250000,
    bedrooms: 2,
    bathrooms: 2,
    area: 125,
    address: "Elandsgracht 56",
    city: "Amsterdam",
    postal_code: "1016 SG",
    property_type: "apartment",
    status: "available",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93687?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1502672260266-1c1ef2d93687?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: false,
    created_at: "2026-04-08T10:00:00Z",
    year_built: 1890,
    energy_label: "C",
    floors: 2,
    furnished: true,
    garden: false,
    balcony: true,
    terrace: false,
    parking: false,
    elevator: false,
    basement: false,
  },
  {
    id: 4,
    title: "Waterfront Villa in IJburg",
    description: "A stunning 320m² modern waterfront villa on IJburg, designed by renowned Dutch architect MVRDV. Five bedrooms, four bathrooms, a private dock, and a floating terrace. The open-plan living space with 6-meter ceilings overlooks the IJmeer. Underfloor heating, solar panels, and a heat pump make this a sustainable luxury home. Includes a two-car garage.",
    price: 2100000,
    bedrooms: 5,
    bathrooms: 4,
    area: 320,
    address: "Diemerparklaan 12",
    city: "Amsterdam",
    postal_code: "1087 KJ",
    property_type: "villa",
    status: "available",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1600585153490-76fb20a32601?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    created_at: "2026-04-05T10:00:00Z",
    year_built: 2019,
    energy_label: "A",
    floors: 2,
    furnished: false,
    garden: true,
    garden_area: 120,
    balcony: false,
    terrace: true,
    parking: true,
    parking_spaces: 2,
    elevator: false,
    basement: false,
  },
  {
    id: 5,
    title: "De Pijp Townhouse",
    description: "A charming 180m² townhouse in vibrant De Pijp, completely renovated in 2025. Three bedrooms, two bathrooms, and a sunny roof terrace with views over the Albert Cuyp market. The ground floor features an open kitchen-diner leading to a courtyard garden. Perfect for families who want to be in the center of Amsterdam's most dynamic neighborhood.",
    price: 1450000,
    bedrooms: 3,
    bathrooms: 2,
    area: 180,
    address: "Gerard Doustraat 88",
    city: "Amsterdam",
    postal_code: "1072 VW",
    property_type: "house",
    status: "available",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600210491892-03d54c0aaf87?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585153490-76fb20a32601?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: false,
    created_at: "2026-04-01T10:00:00Z",
    year_built: 1905,
    energy_label: "B",
    floors: 3,
    furnished: false,
    garden: true,
    garden_area: 25,
    balcony: false,
    terrace: true,
    parking: false,
    elevator: false,
    basement: true,
  },
  {
    id: 6,
    title: "Oud-West Loft Conversion",
    description: "An impressive 195m² loft in a converted 1920s school building in Oud-West. Original steel-framed windows, 4-meter ceilings, and polished concrete floors create an industrial-chic atmosphere. Two large bedrooms, a walk-in closet, and a chef's kitchen with Gaggenau appliances. The shared courtyard garden is professionally landscaped. Located on Bilderdijkstraat, surrounded by independent boutiques and restaurants.",
    price: 1350000,
    bedrooms: 2,
    bathrooms: 2,
    area: 195,
    address: "Bilderdijkstraat 142",
    city: "Amsterdam",
    postal_code: "1053 LA",
    property_type: "apartment",
    status: "under-consideration",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: false,
    created_at: "2026-03-28T10:00:00Z",
    year_built: 1925,
    energy_label: "C",
    floors: 1,
    furnished: true,
    garden: false,
    balcony: false,
    terrace: false,
    parking: false,
    elevator: true,
    basement: false,
  },
  {
    id: 7,
    title: "Oosterpark Estate",
    description: "A magnificent 450m² family estate on the edge of Oosterpark. Built in 1895 and sensitively modernized, this home retains its stained glass, parquet floors, and ornate staircases. Six bedrooms, four bathrooms, a wine cellar, and a 800m² walled garden. A separate coach house serves as a guest apartment or home office. One of Amsterdam's finest period homes.",
    price: 4500000,
    bedrooms: 6,
    bathrooms: 4,
    area: 450,
    address: "Oosterpark 18",
    city: "Amsterdam",
    postal_code: "1091 AB",
    property_type: "villa",
    status: "available",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585152915-d208bef86737?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    created_at: "2026-03-20T10:00:00Z",
    year_built: 1895,
    energy_label: "D",
    floors: 3,
    furnished: false,
    garden: true,
    garden_area: 800,
    balcony: false,
    terrace: false,
    parking: true,
    parking_spaces: 2,
    elevator: false,
    basement: true,
  },
  {
    id: 8,
    title: "Plantage Studio Apartment",
    description: "A cleverly designed 65m² studio in the leafy Plantage neighborhood. Custom-built furniture maximizes every square meter, with a Murphy bed, hidden storage, and a compact but fully equipped kitchen. Large windows overlook the Artis Zoo gardens. Perfect for a pied-à-terre or investment property in one of Amsterdam's most charming and quiet districts.",
    price: 485000,
    bedrooms: 1,
    bathrooms: 1,
    area: 65,
    address: "Plantage Kerklaan 32",
    city: "Amsterdam",
    postal_code: "1018 CZ",
    property_type: "studio",
    status: "available",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1616486338812-3dadae4b4f9d?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: false,
    created_at: "2026-03-15T10:00:00Z",
    year_built: 1955,
    energy_label: "C",
    floors: 1,
    furnished: true,
    garden: false,
    balcony: true,
    terrace: false,
    parking: false,
    elevator: false,
    basement: false,
  },
  {
    id: 9,
    title: "Westerpark Modern Family Home",
    description: "A contemporary 240m² family home in Westerpark, completed in 2024. Four bedrooms, three bathrooms, a home cinema, and a landscaped garden with a pergola-covered dining area. The kitchen features a Molteni island and integrated appliances. Sustainable construction with triple glazing, air-source heat pump, and rainwater harvesting. Walking distance to Westerpark and the Haarlemmerdijk shops.",
    price: 1850000,
    bedrooms: 4,
    bathrooms: 3,
    area: 240,
    address: "Van Hogendorpstraat 44",
    city: "Amsterdam",
    postal_code: "1013 AZ",
    property_type: "house",
    status: "sold",
    listing_type: "sale",
    image_url: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600607687644-c7171b42498b?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: false,
    created_at: "2026-03-10T10:00:00Z",
    year_built: 2024,
    energy_label: "A++",
    floors: 3,
    furnished: false,
    garden: true,
    garden_area: 60,
    balcony: false,
    terrace: true,
    parking: true,
    parking_spaces: 1,
    elevator: false,
    basement: false,
  },
  {
    id: 10,
    title: "Canal View Apartment for Rent",
    description: "A stunning 90m² two-bedroom apartment overlooking the Keizersgracht canal. High ceilings, original features, and a modern kitchen. Fully furnished with designer pieces. Perfect for expats seeking an authentic Amsterdam experience.",
    price: 3850,
    bedrooms: 2,
    bathrooms: 1,
    area: 90,
    address: "Keizersgracht 412",
    city: "Amsterdam",
    postal_code: "1016 GC",
    property_type: "apartment",
    status: "available",
    listing_type: "rent",
    image_url: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    created_at: "2026-04-20T10:00:00Z",
    year_built: 1895,
    energy_label: "C",
    floors: 2,
    furnished: true,
    garden: false,
    balcony: true,
    terrace: false,
    parking: false,
    elevator: false,
    basement: false,
  },
  {
    id: 11,
    title: "Modern Loft in Oud-West",
    description: "A spacious 120m² loft in a converted industrial building. Two bedrooms, two bathrooms, and a private rooftop terrace. Open-plan living with exposed beams and polished concrete floors. Available immediately for long-term rent.",
    price: 4200,
    bedrooms: 2,
    bathrooms: 2,
    area: 120,
    address: "Bilderdijkstraat 88",
    city: "Amsterdam",
    postal_code: "1053 KM",
    property_type: "loft",
    status: "available",
    listing_type: "rent",
    image_url: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1616486029423-aaa4789e8c9a?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: false,
    created_at: "2026-04-18T10:00:00Z",
    year_built: 1920,
    energy_label: "B",
    floors: 1,
    furnished: false,
    garden: false,
    balcony: false,
    terrace: true,
    parking: true,
    parking_spaces: 1,
    elevator: true,
    basement: false,
  },
  {
    id: 12,
    title: "Family Home in Plantage",
    description: "A charming 160m² three-bedroom family home near Artis Zoo. Large garden, two bathrooms, and a finished basement. Quiet street with excellent schools nearby. Perfect for families relocating to Amsterdam. Available furnished or unfurnished.",
    price: 5500,
    bedrooms: 3,
    bathrooms: 2,
    area: 160,
    address: "Plantage Middenlaan 45",
    city: "Amsterdam",
    postal_code: "1018 DB",
    property_type: "house",
    status: "available",
    listing_type: "rent",
    image_url: "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1200&q=80",
    images: [
      "https://images.unsplash.com/photo-1600585154363-67eb9e2e2099?auto=format&fit=crop&w=1200&q=80",
      "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80",
    ],
    featured: true,
    created_at: "2026-04-16T10:00:00Z",
    year_built: 1910,
    energy_label: "D",
    floors: 2,
    furnished: true,
    garden: true,
    garden_area: 80,
    balcony: false,
    terrace: false,
    parking: true,
    parking_spaces: 1,
    elevator: false,
    basement: true,
  },
];
